SAVED_MODEL_PATH: '' #'/home/jovyan/nas/1_user/eunsung.shin@agilesoda.ai/module/CRAFTS/pretrain/TRBA_best_acc_210629.pth'                       # path to model to continue training

# DATA PROCESSING
imgH: 16                                   # the height of the input image
imgW: 64                                  # the width of the input image
CHAR_PATH: './char_dicts/charset-kor-sp.txt' # path to character label
MAX_BATCH_LENGTH: 16                       # the number of word bbox sampled from one image
PAD: ''
# MODEL ARCHITECTURE
Transformation: 'TPS'                      # Transformation stage. None|TPS
FeatureExtraction: 'SimpleResNet'                # FeatureExtraction stage. VGG|RCNN|ResNet|SimpleResNet
SequenceModeling: 'BiLSTM'                 # SequenceModeling stage. None|BiLSTM
Prediction: 'Attn'                         # Prediction stage. CTC|Attn
num_fiducial: 20                           # number of fiducial points of TPS-STN
input_channel: 130                          # the number of input channel of Feature extractor
output_channel: 512                        # the number of output channel of Feature extractor
hidden_size: 256                           # the size of the LSTM hidden state
baiduCTC : True                            # for data_filtering_off mode
batch_max_length : 25                      # max length of batch
cropped_batch_len : 32                     # max length of cropped batch



# parser.add_argument('--saved_model', default='', help="path to model to continue training")
# parser.add_argument('--FT', action='store_true', help='whether to do fine-tuning')
# parser.add_argument('--adam', action='store_true', help='Whether to use adam (default is Adadelta)')
# parser.add_argument('--lr', type=float, default=1, help='learning rate, default=1.0 for Adadelta')
# parser.add_argument('--beta1', type=float, default=0.9, help='beta1 for adam. default=0.9')
# parser.add_argument('--rho', type=float, default=0.95, help='decay rate rho for Adadelta. default=0.95')
# parser.add_argument('--eps', type=float, default=1e-8, help='eps for Adadelta. default=1e-8')
# parser.add_argument('--grad_clip', type=float, default=5, help='gradient clipping value. default=5')
# parser.add_argument('--baiduCTC', action='store_true', help='for data_filtering_off mode')
# """ Data processing """
# parser.add_argument('--select_data', type=str, default='MJ-ST',
#                     help='select training data (default is MJ-ST, which means MJ and ST used as training data)')
# parser.add_argument('--batch_ratio', type=str, default='0.5-0.5',
#                     help='assign ratio for each selected data in the batch')
# parser.add_argument('--total_data_usage_ratio', type=str, default='1.0',
#                     help='total data usage ratio, this ratio is multiplied to total number of data.')
# parser.add_argument('--batch_max_length', type=int, default=25, help='maximum-label-length')
# parser.add_argument('--imgH', type=int, default=32, help='the height of the input image')
# parser.add_argument('--imgW', type=int, default=100, help='the width of the input image')
# parser.add_argument('--rgb', action='store_true', help='use rgb input')
# parser.add_argument('--character', type=str,
#                     default='0123456789abcdefghijklmnopqrstuvwxyz', help='character label')
# parser.add_argument('--sensitive', action='store_true', help='for sensitive character mode')
# parser.add_argument('--PAD', action='store_true', help='whether to keep ratio then pad for image resize')
# parser.add_argument('--data_filtering_off', action='store_true', help='for data_filtering_off mode')
# """ Model Architecture """
# parser.add_argument('--Transformation', type=str, default = 'TPS', help='Transformation stage. None|TPS')
# parser.add_argument('--FeatureExtraction', type=str, default = 'ResNet',
#                     help='FeatureExtraction stage. VGG|RCNN|ResNet')
# parser.add_argument('--SequenceModeling', type=str, default = 'BiLSTM', help='SequenceModeling stage. None|BiLSTM')
# parser.add_argument('--Prediction', type=str, default = 'Attn',  help='Prediction stage. CTC|Attn')
# parser.add_argument('--num_fiducial', type=int, default=20, help='number of fiducial points of TPS-STN')
# parser.add_argument('--input_channel', type=int, default=34,
#                     help='the number of input channel of Feature extractor')
# parser.add_argument('--output_channel', type=int, default=512,
#                     help='the number of output channel of Feature extractor')
# parser.add_argument('--hidden_size', type=int, default=256, help='the size of the LSTM hidden state')
#  opt.character
# batch_max_length